---
title: 'STATS 20: Homework 5 Assignment'
author: "Brandon Liu"
date: "2025-02-25"
output:
  pdf_document:
    toc: true
    toc_depth: '4'
  html_document:
    toc: true
    toc_depth: 4
    toc_float: true
    code_folding: show
  word_document:
    toc: true
    toc_depth: '4'
---
\newpage

## Question 1
```{r Question 1a}
# create a minimum coins function
n_coins <- function(cents = 0) {
  quarters <- cents %/% 25
  amount_remaining <- cents %% 25
  dimes <- amount_remaining %/% 10
  amount_remaining <- amount_remaining %% 10
  nickels <- amount_remaining %/% 5
  amount_remaining <- amount_remaining %% 5
  pennies <- amount_remaining
  n_coins <- quarters + dimes + nickels + pennies
  return(n_coins)
}
n_coins()
```

```{r Question 1b}
# create a minimum coins function
n_coins <- function(cents = 0) {
  quarters <- cents %/% 25
  amount_remaining <- cents %% 25
  dimes <- amount_remaining %/% 10
  amount_remaining <- amount_remaining %% 10
  nickels <- amount_remaining %/% 5
  amount_remaining <- amount_remaining %% 5
  pennies <- amount_remaining
  n_coins <- quarters + dimes + nickels + pennies
  return(n_coins)
}
n_coins(cents = 4)
```

```{r Question 1c}
# create a minimum coins function
n_coins <- function(cents = 0) {
  quarters <- cents %/% 25
  amount_remaining <- cents %% 25
  dimes <- amount_remaining %/% 10
  amount_remaining <- amount_remaining %% 10
  nickels <- amount_remaining %/% 5
  amount_remaining <- amount_remaining %% 5
  pennies <- amount_remaining
  n_coins <- quarters + dimes + nickels + pennies
  return(n_coins)
}
n_coins(cents = 47)
```

```{r Question 1d}
# create a minimum coins function
n_coins <- function(cents = 0) {
  quarters <- cents %/% 25
  amount_remaining <- cents %% 25
  dimes <- amount_remaining %/% 10
  amount_remaining <- amount_remaining %% 10
  nickels <- amount_remaining %/% 5
  amount_remaining <- amount_remaining %% 5
  pennies <- amount_remaining
  n_coins <- quarters + dimes + nickels + pennies
  return(n_coins)
}
n_coins(cents = 99)
```

```{r Question 1e}
# create a minimum coins function
n_coins <- function(cents = 0) {
  quarters <- cents %/% 25
  amount_remaining <- cents %% 25
  dimes <- amount_remaining %/% 10
  amount_remaining <- amount_remaining %% 10
  nickels <- amount_remaining %/% 5
  amount_remaining <- amount_remaining %% 5
  pennies <- amount_remaining
  n_coins <- quarters + dimes + nickels + pennies
  return(n_coins)
}
n_coins(1:99)
```
\newpage

## Question 2
```{r Question 2a}
# create a minimum function
my_min <- function(vec, na.rm = FALSE) {
  if (na.rm) { # if na.rm is TRUE, remove NA values
    vec <- vec[!is.na(vec)]
  }
  if (any(is.na(vec))) {
    return(NA)
  }
  if (length(vec) == 0) {
    return(Inf)
  }
  min_value <- vec[1]
  for (i in seq_along(vec)) {
    if (vec[i] < min_value) {
      min_value <- vec[i]
    }
  }
  return(min_value)
}
my_min(c(4, 1, 0, 2, -3, -5, -4))
```

```{r Question 2b}
# create a minimum function
my_min <- function(vec, na.rm = FALSE) {
  if (na.rm) { # if na.rm is TRUE, remove NA values
    vec <- vec[!is.na(vec)]
  }
   if (any(is.na(vec))) {
    return(NA)
   }
  if (length(vec) == 0) {
    return(Inf)
  }
  min_value <- vec[1]
  for (i in seq_along(vec)) {
    if (vec[i] < min_value) {
      min_value <- vec[i]
    }
  }
  return(min_value)
}
my_min(c("bears", "beets", "Battlestar Galactica"))
```

```{r Question 2c}
# create a minimum function
my_min <- function(vec, na.rm = FALSE) {
  if (na.rm) { # if na.rm is TRUE, remove NA values
    vec <- vec[!is.na(vec)]
  }
  if (any(is.na(vec))) {
    return(NA)
  }
  if (length(vec) == 0) {
    return(Inf)
  }
  min_value <- vec[1]
  for (i in seq_along(vec)) {
    if (vec[i] < min_value) {
      min_value <- vec[i]
    }
  }
  return(min_value)
}
my_min(7)
```

```{r Question 2d}
# create a minimum function
my_min <- function(vec, na.rm = FALSE) {
  if (na.rm) { # if na.rm is TRUE, remove NA values
    vec <- vec[!is.na(vec)]
  }
  if (any(is.na(vec))) {
    return(NA)
  }
  if (length(vec) == 0) {
    return(Inf)
  }
  min_value <- vec[1]
  for (i in seq_along(vec)) {
    if (vec[i] < min_value) {
      min_value <- vec[i]
    }
  }
  return(min_value)
}
my_min(c("Pawnee", "rules", "Eagleton", NA), na.rm = TRUE)
```

```{r Question 2e}
# create a minimum function
my_min <- function(vec, na.rm = FALSE) {
  if (na.rm) { # if na.rm is TRUE, remove NA values
    vec <- vec[!is.na(vec)]
  }
  if (any(is.na(vec))) {
    return(NA)
  }
  if (length(vec) == 0) {
    return(Inf)
  }
  min_value <- vec[1]
  for (i in seq_along(vec)) {
    if (vec[i] < min_value) {
      min_value <- vec[i]
    }
  }
  return(min_value)
}
my_min(c("Pawnee", "rules", "Eagleton", NA), na.rm = FALSE)
```

```{r Question 2f}
# create a minimum function
my_min <- function(vec, na.rm = FALSE) {
  if (na.rm) { # if na.rm is TRUE, remove NA values
    vec <- vec[!is.na(vec)]
  }
  if (any(is.na(vec))) {
    return(NA)
  }
  if (length(vec) == 0) {
    return(Inf)
  }
  min_value <- vec[1]
  for (i in seq_along(vec)) {
    if (vec[i] < min_value) {
      min_value <- vec[i]
    }
  }
  return(min_value)
}
my_min(NA, na.rm = TRUE)
```

```{r Question 2g}
# create a minimum function
my_min <- function(vec, na.rm = FALSE) {
  if (na.rm) { # if na.rm is TRUE, remove NA values
    vec <- vec[!is.na(vec)]
  }
  if (any(is.na(vec))) {
    return(NA)
  }
  if (length(vec) == 0) {
    return(Inf)
  }
  min_value <- vec[1]
  for (i in seq_along(vec)) {
    if (vec[i] < min_value) {
      min_value <- vec[i]
    }
  }
  return(min_value)
}
my_min(NA, na.rm = FALSE)
```
\newpage

## Question 3
```{r Question 3a}
# create a my_lapply() function
my_lapply <- function(X = test_list, FUN = length, ...) {
  result <- list() # initialize result as an empty list
  for (i in seq_along(X)) {
    result[[i]] <- FUN(X[[i]], ...) # output each element of X as a vectorized list
  }
  names(result) <- names(X) # preserve the names of X in result
  return(result)
}
test_list <- list(one = 1.1, two = c(1.1, 2.2), three = c(1.1, 2.2, 3.3))
my_lapply(X = unname(test_list), FUN = length)
```

```{r Question 3b}
# create a my_lapply() function
my_lapply <- function(X = test_list, FUN = length, ...) {
  result <- list() # initialize result as an empty list
  for (i in seq_along(X)) {
    result[[i]] <- FUN(X[[i]], ...) # ensure extra arguments are passed in
  }
  names(result) <- names(X) # preserve the names of X in result
  return(result)
}
test_list <- list(one = 1.1, two = c(1.1, 2.2), three = c(1.1, 2.2, 3.3))
# make sure your output is an unnamed list if the input is unnamed
my_lapply(X = test_list, FUN = length)
```

```{r Question 3c}
# create a my_lapply() function
my_lapply <- function(X = test_list, FUN = length, ...) {
  result <- list() # initialize result as an empty list
  for (i in seq_along(X)) {
    result[[i]] <- FUN(X[[i]], ...) # ensure extra arguments are passed in
  }
  names(result) <- names(X) # preserve the names of X in result
  return(result)
}
test_list <- list(one = 1.1, two = c(1.1, 2.2), three = c(1.1, 2.2, 3.3))
# make sure your output is an unnamed list if the input is unnamed
my_lapply(X = test_list, FUN = round, digits = 0)
```
\newpage

## Question 4
```{r Question 4a}
# create a my_vapply() function
my_vapply <- function(X = test_list, FUN = length, FUN.VALUE = numeric(1), ...) {
  if (length(FUN.VALUE) == 1) {
    result <- numeric(length(X))
    # if length of FUN.VALUE = 1, return a numeric vector, preserving col names
  }
  else {
    result <- matrix(nrow = length(FUN.VALUE), ncol = length(X))
    # if length of X > 1, return a matrix, preserving col & adding row names
  }
  result <- matrix() # initialize result as an empty list
  for (i in seq_along(X)) {
    result[[i]] <- FUN(X[[i]], ...) # ensure extra arguments are passed in
  }
  names(result) <- names(X) # preserve the names of X in result
  return(result)
}
test_list <- list(one = 1.1, two = c(1.1, 2.2), three = c(1.1, 2.2, 3.3))
# make sure your output is an unnamed list if the input is unnamed
my_vapply(X = unname(test_list), FUN = length, FUN.VALUE = numeric(1))
```

```{r Question 4b}
# create a my_vapply() function
my_vapply <- function(X = test_list, FUN = length, FUN.VALUE = numeric(1), ...) {
  if (length(FUN.VALUE) == 1) {
    result <- numeric(length(X))
    # if length of FUN.VALUE = 1, return a numeric vector, preserving col names
  }
  else {
    result <- matrix(nrow = length(FUN.VALUE), ncol = length(X))
    # if length of X > 1, return a matrix, preserving col & adding row names
  }
  result <- matrix() # initialize result as an empty list
  for (i in seq_along(X)) {
    result[[i]] <- FUN(X[[i]], ...) # ensure extra arguments are passed in
  }
  names(result) <- names(X) # preserve the names of X in result
  return(result)
}
test_list <- list(one = 1.1, two = c(1.1, 2.2), three = c(1.1, 2.2, 3.3))
# make sure your output is an unnamed list if the input is unnamed
my_vapply(X = test_list, FUN = length, FUN.VALUE = numeric(1))
```

```{r Question 4c}
# create a my_vapply() function
my_vapply <- function(X, FUN, FUN.VALUE, ...) {
  if (length(FUN.VALUE) == 1) {
    result <- numeric(length(X))
    # if length of FUN.VALUE = 1, return a numeric vector, preserving col names
  }
  else {
    result <- matrix(nrow = length(FUN.VALUE), ncol = length(X))
    # if length of X > 1, return a matrix, preserving col & adding row names
  }
  result <- matrix(nrow = length(FUN.VALUE), ncol = length(X))
  # initialize result as a matrix w/ row = output length & col = input length
  for (i in seq_along(X)) {
    result[, i] <- FUN(X[[i]], ...) # ensure extra arguments are passed in
  }
  colnames(result) <- names(X) # preserve the names of X in result
  return(result)
}
test_list <- list(one = 1.1, two = c(1.1, 2.2), three = c(1.1, 2.2, 3.3))
# make sure your output is an unnamed list if the input is unnamed
my_vapply(X = test_list, FUN = range, FUN.VALUE = numeric(2))
```

```{r Question 4d}
# create a vapply() function
my_vapply <- function(X, FUN, FUN.VALUE, ...) {
  if (length(FUN.VALUE) == 1) {
    result <- numeric(length(X))
    # if length of FUN.VALUE = 1, return a numeric vector, preserving col names
  }
  else {
    result <- matrix(nrow = length(FUN.VALUE), ncol = length(X))
    # if length of X > 1, return a matrix, preserving col & adding row names
  }
  result <- matrix() # initialize result as an empty list
  for (i in seq_along(X)) {
    result[[i]] <- FUN(X[[i]], ...) # ensure extra arguments are passed in
  }
  names(result) <- names(X) # preserve the names of X in result
  return(result)
}
test_list <- list(one = 1.1, two = c(1.1, 2.2), three = c(1.1, 2.2, 3.3))
# make sure your output is an unnamed list if the input is unnamed
my_vapply(X = list(1.11, 2.22, 3.33), FUN = round, FUN.VALUE = numeric(1), 
       digits = 0)
```
\newpage

## Question 5
```{r Question 5a}
# create a my_scale() function using attributes and min-max scaling
my_scale <- function (x, a = NULL, b = NULL) {
  # if "a" and "b" attributes are not available, scale to [0,1]
  if (is.null(a) || is.null(b)) {
    min_x <- min(x, na.rm = TRUE)
    max_x <- max(x, na.rm = TRUE)
    scaled_x <- (x - min_x) / (max_x - min_x)
    attr(scaled_x, "a") <- 0 # assign 0 to attribute "a" of scaled_x
    attr(scaled_x, "b") <- 1 # assign 1 to attribute "b" of scaled_x
  }
  # if "a" and "b" attributes are available, scale to [a, b]
  else {
    min_x <- min(x, na.rm = TRUE)
    max_x <- max(x, na.rm = TRUE)
    scaled_x <- a + ((x - min_x) * (b - a) / (max_x - min_x))
    attr(scaled_x, "a") <- a # assign a to attribute "a" of scaled_x
    attr(scaled_x, "b") <- b # assign b to attribute "b" of scaled_x
  }
  return(scaled_x)
}
my_scale(x = c(1, 2, 3, 4, 5)) # a and b are defaulted to be NULL
```

```{r Question 5b}
# create a my_scale() function using attributes and min-max scaling
my_scale <- function (x, a = NULL, b = NULL) {
  # if "a" and "b" attributes are not available, scale to [0,1]
  if (is.null(a) || is.null(b)) {
    min_x <- min(x, na.rm = TRUE)
    max_x <- max(x, na.rm = TRUE)
    scaled_x <- (x - min_x) / (max_x - min_x)
    attr(scaled_x, "a") <- 0 # assign 0 to attribute "a" of scaled_x
    attr(scaled_x, "b") <- 1 # assign 1 to attribute "b" of scaled_x
  }
  # if "a" and "b" attributes are available, scale to [a, b]
  else {
    min_x <- min(x, na.rm = TRUE)
    max_x <- max(x, na.rm = TRUE)
    scaled_x <- a + ((x - min_x) * (b - a) / (max_x - min_x))
    attr(scaled_x, "a") <- a # assign a to attribute "a" of scaled_x
    attr(scaled_x, "b") <- b # assign b to attribute "b" of scaled_x
  }
  return(scaled_x)
}
my_scale(x = c(1, 2, 3, 4, 5), a = 2, b = 3) # defining a and b overrides NULL
```

```{r Question 5c}
# create a my_scale() function using attributes and min-max scaling
my_scale <- function (x, a = NULL, b = NULL) {
  # if "a" and "b" attributes are not available, scale to [0,1]
  if (is.null(a) || is.null(b)) {
    min_x <- min(x, na.rm = TRUE)
    max_x <- max(x, na.rm = TRUE)
    scaled_x <- (x - min_x) / (max_x - min_x)
    attr(scaled_x, "a") <- 0 # assign 0 to attribute "a" of scaled_x
    attr(scaled_x, "b") <- 1 # assign 1 to attribute "b" of scaled_x
  }
  # if "a" and "b" attributes are available, scale to [a, b]
  else {
    min_x <- min(x, na.rm = TRUE)
    max_x <- max(x, na.rm = TRUE)
    scaled_x <- a + ((x - min_x) * (b - a) / (max_x - min_x))
    attr(scaled_x, "a") <- a # assign a to attribute "a" of scaled_x
    attr(scaled_x, "b") <- b # assign b to attribute "b" of scaled_x
  }
  return(scaled_x)
}
my_scale(x = c(1, 2, 3, 4, 5), a = 19, b = 25) # defining a and b overrides NULL
```
\newpage

## Question 6
(a)
```{r Question 6a}
# create a my_ifelse() function
my_ifelse <- function (test, yes, no) {
  # recycle yes and no to match the length of the test if necessary
  yes <- rep(yes, length(test)) # recycle yes for the length of the test
  no <- rep(no, length(test)) # recycle no for the length of the test
  
  result <- NULL # initialize an empty vector
  
  for (i in seq_along(test)) { # for each i-th element in test
    if (identical(test[i], TRUE)) { # if test's i-th element is TRUE
      # assign corresponding 'yes' elements to each result's i-th element
      result[i] <- yes[i]
    }
    else { # if test's i-th element is FALSE
      # assign corresponding 'no' elements to each result's i-th element
      result[i] <- no[i]
    }
  }
  return(result)
}
my_ifelse(test = c(TRUE, FALSE, FALSE, TRUE), yes = "YES", no = "NO")
```

(b)
```{r Question 6b(i)}
# verify that my_ifelse() works for the following command
my_ifelse <- function (test, yes, no) {
  # recycle yes and no to match the length of the test if necessary
  yes <- rep(yes, length(test)) # recycle yes for the length of the test
  no <- rep(no, length(test)) # recycle no for the length of the test
  
  result <- NULL # initialize an empty vector
  
  for (i in seq_along(test)) { # for each i-th element in test
    if (identical(test[i], TRUE)) { # if test's i-th element is TRUE
      # assign corresponding 'yes' elements to each result's i-th element
      result[i] <- yes[i]
    }
    else { # if test's i-th element is FALSE
      # assign corresponding 'no' elements to each result's i-th element
      result[i] <- no[i]
    }
  }
  return(result)
}
x <- (1:10) * pi
my_ifelse(test = x %% 1 >= 0.5, yes = x %/% 1 + 1, no = x %/% 1)
```

```{r Question 6b(ii)}
# verify that my_ifelse() works for the following command
my_ifelse <- function (test, yes, no) {
  # recycle yes and no to match the length of the test if necessary
  yes <- rep(yes, length(test)) # recycle yes for the length of the test
  no <- rep(no, length(test)) # recycle no for the length of the test
  
  result <- NULL # initialize an empty vector
  
  for (i in seq_along(test)) { # for each i-th element in test
    if (identical(test[i], TRUE)) { # if test's i-th element is TRUE
      # assign corresponding 'yes' elements to each result's i-th element
      result[i] <- yes[i]
    }
    else { # if test's i-th element is FALSE
      # assign corresponding 'no' elements to each result's i-th element
      result[i] <- no[i]
    }
  }
  return(result)
}
my_ifelse(test = x %% 1 >= 0.5, yes = 1, no = 0)
```

(c)
```{r Question 6c(i)}
# create a my_abs() function [absolute value]
my_abs <- function (x) {
  result <- NULL # initialize an empty vector
  for (i in seq_along(x)) { # for each i-th element in x
    if (x[i] < 0) { # if x's i-th element is TRUE
      # assign corresponding 'yes' elements to each result's i-th element
      result[i] <- x[i] * (-1)
    }
    else { # if x's i-th element is FALSE
      # assign corresponding 'no' elements to each result's i-th element
      result[i] <- x[i]
    }
  }
  return(result)
}
my_abs(x = c(1, -2, 3, -4, 5))
```

```{r Question 6c(ii)}
# create a my_sign() function [positive (+) / negative (-)]
my_sign <- function (x, positive, negative) {
  # recycle positive and negative to match the length of the test if necessary
  positive <- rep(positive, length(x)) # recycle positive for the length of x
  negative <- rep(negative, length(x)) # recycle negative for the length of x
  
  result <- NULL # initialize an empty vector
  
  for (i in seq_along(x)) { # for each i-th element in x
    if (x[i] < 0) { # if x's i-th element is TRUE
      # assign corresponding 'negative' elements to each result's i-th element
      result[i] <- negative[i]
    }
    else { # if x's i-th element is FALSE
      # assign corresponding 'positive' elements to each result's i-th element
      result[i] <- positive[i]
    }
  }
  return(result)
}
my_sign(x = c(1, -2, 3, -4, 5), positive = "Positive", negative = "Negative")
```
\newpage

## Question 7
(a)
```{r Question 7a}
bubble_sort <- function (x) {
  if (length(x) > 1) {
    swapped <- TRUE
    while(swapped) {
      swapped <- FALSE
      for (i in 1:(length(x) - 1)) {
        if (x[i] > x[i + 1]) {
          # retain current element value by storing it in a temporary object
          temp <- x[i]
          # assign the next element to the current position
          x[i] <- x[i + 1]
          # assign the current element (stored in temp) to the next position
          x[i + 1] <- temp
          swapped <- TRUE
        }
      }
    }
  }
  return(x)
}
```

(b)
```{r Question 7b(i)}
# test the bubble_sort() function
bubble_sort <- function (x) {
  if (length(x) > 1) {
    swapped <- TRUE
    while(swapped) {
      swapped <- FALSE
      for (i in 1:(length(x) - 1)) {
        if (x[i] > x[i + 1]) {
          # retain current element value by storing it in a temporary object
          temp <- x[i]
          # assign the next element to the current position
          x[i] <- x[i + 1]
          # assign the current element (stored in temp) to the next position
          x[i + 1] <- temp
          swapped <- TRUE
        }
      }
    }
  }
  return(x)
}
bubble_sort(numeric(0))
```

```{r Question 7b(ii)}
# test the bubble_sort() function
bubble_sort <- function (x) {
  if (length(x) > 1) {
    swapped <- TRUE
    while(swapped) {
      swapped <- FALSE
      for (i in 1:(length(x) - 1)) {
        if (x[i] > x[i + 1]) {
          # retain current element value by storing it in a temporary object
          temp <- x[i]
          # assign the next element to the current position
          x[i] <- x[i + 1]
          # assign the current element (stored in temp) to the next position
          x[i + 1] <- temp
          swapped <- TRUE
        }
      }
    }
  }
  return(x)
}
bubble_sort(7)
```

```{r Question 7b(iii)}
# test the bubble_sort() function
bubble_sort <- function (x) {
  if (length(x) > 1) {
    swapped <- TRUE
    while(swapped) {
      swapped <- FALSE
      for (i in 1:(length(x) - 1)) {
        if (x[i] > x[i + 1]) {
          # retain current element value by storing it in a temporary object
          temp <- x[i]
          # assign the next element to the current position
          x[i] <- x[i + 1]
          # assign the current element (stored in temp) to the next position
          x[i + 1] <- temp
          swapped <- TRUE
        }
      }
    }
  }
  return(x)
}
bubble_sort(10:1)
```

```{r Question 7b(iv)}
# test the bubble_sort() function
bubble_sort <- function (x) {
  if (length(x) > 1) {
    swapped <- TRUE
    while(swapped) {
      swapped <- FALSE
      for (i in 1:(length(x) - 1)) {
        if (x[i] > x[i + 1]) {
          # retain current element value by storing it in a temporary object
          temp <- x[i]
          # assign the next element to the current position
          x[i] <- x[i + 1]
          # assign the current element (stored in temp) to the next position
          x[i + 1] <- temp
          swapped <- TRUE
        }
      }
    }
  }
  return(x)
}
bubble_sort(c("Stats 20", "I", "love"))
```
\newpage

## Question 8
```{r Question 8}
my_unlist <- function (x) {
  for (i in seq_along(x)) {
    if (is.factor(x) == TRUE) {
      factor(x) <- levels(x)
    }
    else {
      c(x[i])
    }
  }
  return(x)
}
```

```{r Question 8a}
# create a my_unlist() function with several mode types
my_unlist <- function(x) {
  result <- c()  # Initialize empty vector
  character_present <- FALSE
  
  for (i in seq_along(x)) {
    if (is.character(x[[i]])) {  
      character_present <- TRUE
      break
    }
  }
  for (i in seq_along(x)) {
    component <- x[[i]]
    if (character_present == TRUE) {
      component <- as.character(component)
    }
  result <- c(result, component)
  }
  result
}
my_unlist(list(c(TRUE, FALSE, TRUE), FALSE, c(TRUE, FALSE, TRUE)))
```

```{r Question 8b}
# create a my_unlist() function with several mode types
my_unlist <- function(x) {
  result <- c()  # Initialize empty vector
  character_present <- FALSE
  
  for (i in seq_along(x)) {
    if (is.character(x[[i]])) {  
      character_present <- TRUE
      break
    }
  }
  for (i in seq_along(x)) {
    component <- x[[i]]
    if (character_present == TRUE) {
      component <- as.character(component)
    }
  result <- c(result, component)
  }
  result
}
my_unlist(list(c(2, 1, 1), c(3, 2, 1), 2))
```

```{r Question 8c}
# create a my_unlist() function with several mode types
my_unlist <- function(x) {
  result <- c()  # Initialize empty vector
  character_present <- FALSE
  
  for (i in seq_along(x)) {
    if (is.character(x[[i]])) {  
      character_present <- TRUE
      break
    }
  }
  for (i in seq_along(x)) {
    component <- x[[i]]
    if (character_present == TRUE) {
      component <- as.character(component)
    }
  result <- c(result, component)
  }
  result
}
my_unlist(list(c(2, 1, 1), c(TRUE, FALSE, TRUE), "text"))
```
