---
title: "STATS 20: Week 3 Discussion Assignment"
author: "<Brandon Liu>"
date: "`r format(Sys.Date(), '%D')`"
output:
  pdf_document:
    toc: true
    toc_depth: '4'
  html_document:
    toc: true
    toc_depth: 4
    toc_float: true
    code_folding: show
---
\newpage

## Problem 1
(a)
```{r Problem 1a}
x <- 1:10
y <- 11:19

x[3] + y[4]
```
(b)
```{r Problem 1b}
sum(x[1:4])
```
(c)
```{r Problem 1c}
(x[5] * x[10]) / (y[8] - y[5])
```
(d)
```{r Problem 1d}
c(x[6:3])
```
(e)
```{r Problem 1e}
c(y[5], rep(y[1], 3), rep(y[4], 2), y[7])
```
(f)
```{r Problem 1f}
length(x) + length(y)
```
\newpage
## Problem 2
(a)
```{r Problem 2}
x <- seq(from = -10, to = 20, by = 2)
x > 5 | x <= -5
```
(b)
```{r Problem 2b}
x != 10 & x != 11 & x != 12
```
(c)
```{r Problem 2c}
positive_elements <- x[x>0]
length(positive_elements)
```
(d)
```{r Problem 2d}
x[x > 6][1]
```
(e)
```{r Problem 2e}
sum(x[x < 0] * (-1))
```
(f)
```{r Problem 2f}
# NA is NOT the same as NaN
y <- c(0, 1, NA, NaN, NA, Inf)
# output a logical vector of where y contains NA and does not contain NaN
# is.na() can be used on vectors and individual numbers
is.na(y) & !is.nan(y)
```
\newpage
## Problem 3
```{r Problem 3(i)}
# Input one
x <- c(2, 4, NA, NA, 9, NaN, 0)
# outputs only the non-missing elements of x
x[!is.na(x)]
```

```{r Problem 3(ii)}
# Input two
x <- 5:9
x[!is.na(x)]
```
```{r Problem 3(iii)}
# Input three
x <- rep(NA, 10)
x[!is.na(x)]
```

```{r Problem 3(iv)}
# Input four
x <- character(0)
x[!is.na(x)]
```
\newpage
## Problem 4
```{r Problem 4(i)}
# Assign x to a vector
x <- 1:3
# Modify x: replace all missing NA or NaN values with mean(x)
x[is.na(x)] <- mean(x, na.rm = TRUE)
# Run the modified x
x
```
```{r Problem 4(ii)}
x <- c(1, NA, 2, NaN, 3)
# Modify x: replace missing values with the mean of the non-missing values in x
# In this case, the mean of x is 2
x[is.na(x)] <- mean(x, na.rm = TRUE)
x
```

```{r Problem 4(iii)}
# This time, there are no non-missing values in x
x <- c(NA, NA, NA)
# Thus, replacement with mean of non-missing values in x will output NaN values
x[is.na(x)] <- mean(x, na.rm = TRUE)
x
```
\newpage
## Problem 5
(a)
```{r Problem 5a(i)}
# Numbers 1 through 11, reversed, all multiplied by -1
x <- -rev(seq_len(11))
# Let idx_num be the sequence of 1, 2, 3, 4, 5
idx_num <- seq_len(5)
# Extract those first five elements of x
x[idx_num]
```

```{r Problem 5a(ii)}
# Extract the remaining elements of x
# In order to start with the 6th element, add 1 to idx_num[5]
# The value of idx_num[5] is known. When you add 1, 5 + 1 = 6, the 6th element.
# Terminate at the 11th (final) element of x
x[(idx_num[5] + 1):11]
```
(b)
```{r Problem 5b(i)}
# Numbers 1 through 11, reversed, all multiplied by -1
x <- -rev(seq_len(11))
# Logical vector that repeats TRUE 5 times and FALSE 6 times
idx_log <- rep(c(TRUE, FALSE), c(5, 6))
# First 5 elements are TRUE in idx_log, the last 6 elements are FALSE
# Thus, x will only output the first 5 elements
x[idx_log]
```
```{r Problem 5b(ii)}
# Turn first 5 elements FALSE in idx_log, and the last 6 elements TRUE
# Thus, x will only output the last 6 remaining elements
x[!idx_log]
```
\newpage
## Problem 6
```{r Problem 6i}
# test case 1: a1,b1 ; expected output: TRUE
a1 <- 3:6
b1 <- c(3, 4, 5, 6)

# Statement 3: If a1 = b1, no. of TRUEs for a1 = b1 equals no. of elements in a1
# In other words, every elements of a1 is the same as every element of b1
mode(a1) == mode(b1) & length(a1) == length(b1) & sum(a1 == b1) == length(a1)
```

```{r Problem 6ii}
# Test case 2: a2,b2 ; expected output: FALSE
a2 <- c(TRUE, FALSE)
# Convert TRUE to 1 and FALSE to 0. This is the T/F numeric representation.
b2 <- as.numeric(a2)

# Statement 3: If a2 = b2, no. of TRUEs for a2 = b2 equals no. of elements in a2
# In other words, every elements of a2 is the same as every element of b2
mode(a2) == mode(b2) & length(a2) == length(b2) & sum(a2 == b2) == length(a2)
```

```{r Problem 6iii}
# Test case 3: a3,b3 ; expected output: FALSE
# Repeat 9, 8, 7 twice
a3 <- rep(9:7, 2)
b3 <- 9:7

# Statement 3: If a3 = b3, no. of TRUEs for a3 = b3 equals no. of elements in a3
# In other words, every elements of a3 is the same as every element of b3
mode(a3) == mode(b3) & length(a3) == length(b3) & sum(a3 == b3) == length(a3)
```
