---
title: "Stats 20: Week 4 Discussion Assignment"
author: "Brandon Liu"
date: "2025-01-28"
output:
  pdf_document:
    toc: true
    toc_depth: '4'
  html_document:
    toc: true
    toc_depth: 4
    toc_float: true
    code_folding: show
---
\newpage
## Question 1
(a)
```{r Question 1a}
# Numbers 1 through 11, reversed, all multiplied by -1
x <- -rev(seq_len(11))
# Extract every element except the 1st, 5th, 8th, and 11th from x
x[-c(1, 5, 8, 11)]
```
(b)
```{r Question 1b}
# Recreate the binary vector (5 iterations of 3 zero's and 4 one's)
binary_vector <- rep(c(rep(0, 3), rep(1, 4)), times = 5)
binary_vector
```
(c)
```{r Question 1c}
# Convert the binary vector to a factor
binary_factor <- factor(rep(c(rep(0, 3), rep(1, 4)), times = 5))
# Now that the factor is created, modify the levels
# Change from 0 and 1 to Male and Female
levels(binary_factor) <- c("Male", "Female")
# Output the factor vector
binary_factor
```
(c)
```{r Question 1c(i)}
binary_matrix1 <- matrix(binary_factor, nrow = 7, ncol = 5)
binary_matrix1
```
```{r Question 1c(ii)}
binary_matrix2 <- matrix(binary_factor, nrow = 5, ncol = 7)
binary_matrix2
```
```{r Question 1c(iii)}
binary_matrix1[6,]
```
```{r Question 1c(iv)}
binary_matrix2[,3]
```
\newpage
## Question 2
```{r Question 2}
matrix_entries <- c(rep(1, 1), rep(0, 3), rep(0, 1), rep(1, 1), rep(0, 2), rep(0, 2), rep(1, 1), rep(0, 4), rep(1, 1))
identity_matrix <- matrix(matrix_entries, nrow = 4, ncol = 4)
identity_matrix
```
\newpage
## Question 3
```{r Question 3}
# p1 values
p1 <- c(1, 1, 2)

# p2 values
p2 <- c(2, 3, 4)

# Calculate the distance between p1 and p2
d <- sqrt(sum((p1 - p2)^2))
d
```
\newpage
## Question 4
(a)
```{r Question 4a}
# Given x^2 - 3x - 4 = 0, use quadratic formula to find the value of x
a <- 1
b <- -3
c <- -4

# Solution one
x <- ((-b)+sqrt(b^2 - 4 * a * c)) / (2 * a)
x
```
```{r Question 4a(ii)}
# Solution two
x <- ((-b)-sqrt(b^2 - 4 * a * c)) / (2 * a)
x
```

(b)
```{r Question 4b}
# Given x^2 + 2x + 4 = 0, use quadratic formula to find the value of x
a <- 1
b <- 2
c <- 4

# Solution one
x <- ((-b)+sqrt(b^2 - 4 * a * c)) / (2 * a)
x
```
For 4b, I received a "NaN" output. This is because the value of the determinant, that is, b^2 - 4 * a * c, is negative, generating an imaginary number when evaluating. Specifically, the value of the determinant is 2^2 - 4 * 1 * 4 = 4 - 16 = -12. An imaginary number is not a valid number, and is thus outputted as NaN.